# Usar Node.js como imagem base
FROM node:18

# Criar diretório de trabalho
WORKDIR /app

# Copiar arquivos para o container
COPY . .

# Instalar dependências
RUN npm install

# Expor a porta do backend
EXPOSE 3001

# Iniciar a aplicação
CMD ["npm", "run", "start"]
